### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by 0xspade** [imhunterand/ApachSAL#7]
Does it change the parameters from waybackurls like qsreplace of tomnomnom tool?

**Comment by imhunterand** [comment]
of course, you can use it.

**Comment by rudSarkar** [comment]
> Does it change the parameters from waybackurls like qsreplace of tomnomnom tool?

I tried, but it doesn't change waybackurls parameter it just appends the payloads end of the line also it doesn't check if there is already `http` or `https` available.

Example:

```url
http://https://example.com/username/edit/?id=2677956../../../../../etc/passwd
```

CC: @imhunterand

**Comment by imhunterand** [comment]
as the result dont use a ``http`` or ``https`` just a domain ``example.com`` as your target.

**Comment by 0xspade** [comment]
hmm, so after parsing the results from wayback urls we should remove the protocols? is that right? like this

Example:
`example.com/endpoint?param=hello&test=world`

and it will append the payload?

**Comment by imhunterand** [comment]
Hi @0xspade 

The payloads will executed in request-param:
`redacted.com/s.?param=` or `redacted.com/news=dlldkk/idspath=esxpath={payloads}`

**Comment by rudSarkar** [comment]
> Hi @0xspade
> 
> The payloads will executed in request-param: `redacted.com/s.?param=` or `redacted.com/news=dlldkk/idspath=esxpath={payloads}`

Then this tool needs more modification, I will suggest using [regex](https://regex101.com/r/7fSiSC/1) to check if the `_target` variable matches with regex then leave them default URL with HTTP and HTTPS

https://github.com/imhunterand/ApachSAL/blob/7e0e24a644b4047b3c6c7ad8f1c74ee5c462ea4c/modules/request_mrclw.py#L23

If it does not match with regex then add `target_url = self.protocol + '://'+_target` variable

https://github.com/imhunterand/ApachSAL/blob/7e0e24a644b4047b3c6c7ad8f1c74ee5c462ea4c/modules/request_mrclw.py#L18

Yesterday I tried to edit the code for PR but it broke many times due to a lack of code quality style.

**Comment by rudSarkar** [comment]
### RequestMrclw class

In this code I made changes but in main.py there are some spaghetti codes that make a mess while working. 

```python
import re
import time
from socket import timeout
import requests
import urllib
from requests.exceptions import ConnectionError, HTTPError


class RequestMrclw:
    def __init__(self):
        self.protocol = 'https'
        self.timeout = 8
        self.header = {}

    def send_request(self, _target: str, _value_header: str):
        if _target:
            target_url = None
            target_url = self.protocol + '://'+_target
            try:

                start = time.time()

                if re.match("^(http:\/\/|https:\/\/)+", _target):
                    print(_target)
                    obj_urllib = urllib.request.Request(_target)
                    obj_urllib.add_header(
                        "Content-type", "application/x-www-form-urlencoded")
                    obj_urllib.add_header(
                        "User-Agent", 'Mozilla/5.0 (Macintosh; Intel Mac OS X x.y; rv:42.0) Gecko/20100101 Firefox/42.0')
                    obj_request = urllib.request.urlopen(
                        obj_urllib, timeout=self.timeout)
                    obj_request_result = str(
                        obj_request.read().decode('utf-8'))

                    time_final = (f'in {time.time() - start:.2f}s')

                    if obj_request_result:
                        return obj_request.url, obj_request_result, obj_request.status, time_final
                    return _target, 'Empry', obj_request.status, time_final
                else:
                    print(target_url)
                    obj_urllib = urllib.request.Request(target_url)
                    obj_urllib.add_header(
                        "Content-type", "application/x-www-form-urlencoded")
                    obj_urllib.add_header(
                        "User-Agent", 'Mozilla/5.0 (Macintosh; Intel Mac OS X x.y; rv:42.0) Gecko/20100101 Firefox/42.0')
                    obj_request = urllib.request.urlopen(
                        obj_urllib, timeout=self.timeout)
                    obj_request_result = str(
                        obj_request.read().decode('utf-8'))

                    time_final = (f'in {time.time() - start:.2f}s')

                    if obj_request_result:
                        return obj_request.url, obj_request_result, obj_request.status, time_final
                    return target_url, 'Empry', obj_request.status, time_final

            except urllib.error.HTTPError as ehttp:
                return target_url, 'HTTP Error!', ehttp.code, str()
            except timeout:
                return target_url, 'Time!', 'Socket Timed Out', str()
            except urllib.error.URLError as eurl:
                return target_url, 'URL Error!', eurl.reason, str()


RequestMrclw().send_request("hackerone.com", None)
```

### Output of send_request()

<img width="685" alt="Screenshot 2022-08-14 at 4 34 54 PM" src="https://user-images.githubusercontent.com/20747656/184533000-4c1aec19-edfa-4f94-9e70-0fc61e0af646.png">

<img width="729" alt="Screenshot 2022-08-14 at 4 35 18 PM" src="https://user-images.githubusercontent.com/20747656/184533017-dfe76458-e445-4350-b3a2-12b9c553c071.png">

I suggest you implement this fix for this tool it will make more sense while working with waybackurls data.


CC: @imhunterand

**Comment by imhunterand** [comment]
**Hi!** @rudSarkar 
Please make it to ``pull-request`` at this project source for contribute.

Regards,

**Comment by rudSarkar** [comment]
> **Hi!** @rudSarkar Please make it to `pull-request` at this project source for contribute.
> 
> Regards,

But it breaks the `main.py` and returns `URL ERROR!`.
