### ISSUE TITLE
main.py

### ISSUE THREAD

**Issue by Armoo-81** [imhunterand/ApachSAL#8]
File "main.py", line 29
    def str_clear(_value_str:str):
                            ^
SyntaxError: invalid syntax
  
I am getting this error

**Comment by imhunterand** [comment]
can you give more information ?

**Comment by rudSarkar** [comment]
> File "main.py", line 29 def str_clear(_value_str:str): ^ SyntaxError: invalid syntax
> 
> I am getting this error

Try with `python3`

**Comment by imhunterand** [comment]
Problem solved with @rudSarkar
